### ISSUE TITLE
Example is not working

### ISSUE THREAD

**Issue by miduga** [axross/tap-diff#7]
```
Error: Cannot find module 'tapDiff'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/miguel/desarrollo/gamernews-api/test/test.js:4:17)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)```

**Comment by axross** [comment]
Thank you for tell the probrem. This issue is fixed by #8.
